// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// Health provides a mock function with given fields: _a0
func (_m *AuthHandler) Health(_a0 *gin.Context) {
	_m.Called(_a0)
}

// LoginHandler provides a mock function with given fields: _a0
func (_m *AuthHandler) LoginHandler(_a0 *gin.Context) {
	_m.Called(_a0)
}

// LogoutHandler provides a mock function with given fields: _a0
func (_m *AuthHandler) LogoutHandler(_a0 *gin.Context) {
	_m.Called(_a0)
}

// RefreshTokenHandler provides a mock function with given fields: _a0
func (_m *AuthHandler) RefreshTokenHandler(_a0 *gin.Context) {
	_m.Called(_a0)
}

// SignupHandler provides a mock function with given fields: _a0
func (_m *AuthHandler) SignupHandler(_a0 *gin.Context) {
	_m.Called(_a0)
}

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
